import type { CollectionBeforeChangeHook } from "payload";

// Keeps `productCode` mirroring `slug.toUpperCase()` so new products do not
// save with a NULL/empty product code. Runs only when `slug` is in the current
// write — locale-only updates (which omit `slug`) leave the existing value
// alone. Slug itself is generated by slugifyBeforeValidate from the product's
// Chinese title / normalizedName before this hook sees it.
export const setProductCodeFromSlug: CollectionBeforeChangeHook = ({ data }) => {
  if (!data) return data;
  const slug = (data as { slug?: unknown }).slug;
  if (typeof slug === "string" && slug.trim().length > 0) {
    (data as { productCode?: string }).productCode = slug.toUpperCase();
  }
  return data;
};
