/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    customCapabilities: CustomCapability;
    products: Product;
    productVariants: ProductVariant;
    news: News;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'productVariants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customCapabilities: CustomCapabilitiesSelect<false> | CustomCapabilitiesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productVariants: ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh' | 'en' | 'es' | 'ar')
    | ('zh' | 'en' | 'es' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'zh' | 'en' | 'es' | 'ar';
  widgets: {
    'wayon-overview': WayonOverviewWidget;
    'wayon-quick-actions': WayonQuickActionsWidget;
    'wayon-latest-inquiries': WayonLatestInquiriesWidget;
    'wayon-latest-news': WayonLatestNewsWidget;
    'wayon-workflow': WayonWorkflowWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * 图片的文字描述，用于 SEO 和无障碍访问，请简要说明图片内容。
   */
  alt: string;
  caption?: string | null;
  /**
   * 素材用途分类。产品图已由迁移脚本标记为“产品”，其他上传素材请选择对应分类。
   */
  category: 'product' | 'license' | 'showroom' | 'factory' | 'case-sales' | 'case-factory' | 'other';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customCapabilities".
 */
export interface CustomCapability {
  id: string;
  capabilityKey:
    | 'custom-thickness'
    | 'custom-cutting-processing'
    | 'custom-size'
    | 'custom-surface'
    | 'custom-color'
    | 'custom-pattern-design'
    | 'custom-hot-bending'
    | 'custom-logo-branding';
  title: string;
  description?: string | null;
  coverImage?: (string | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 前台产品目录主要读取“系列类型”“产品类型”和“产品规格（型号）”。新增产品时建议顺序：填标题 → 选系列类型 → 上传主图 → 在下方“产品型号”里添加规格 → 打开“发布到前台”。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  slug: string;
  /**
   * 导入产品时生成的族系名称，用作导入识别键。不要手动修改。
   */
  normalizedName?: string | null;
  /**
   * 控制产品是否在官网显示。导入产品会自动发布，手动新建产品默认不发布，内容准备好后再打开。
   */
  published?: boolean | null;
  /**
   * 产品列表卡片和详情页首屏优先使用这张图。如果留空，前台会自动从该产品的第一个型号里取图（优先级：元素图 → 空间图 → 实拍图），列表页的“封面”列也会显示该兜底图。
   */
  image?: (string | null) | Media;
  description?: string | null;
  /**
   * 前台左侧“岩板产品系列 / 特惠系列”从这里读取。需要进入“特惠系列”的产品，请在这里勾选“特惠系列”。
   */
  seriesTypes?:
    | (
        | '质感岩板'
        | '名石岩板'
        | '洞石岩板'
        | '木纹岩板'
        | '护墙岩板'
        | '艺术岩板'
        | '连纹岩板'
        | '创意网红'
        | '新品系列'
        | '特惠系列'
      )[]
    | null;
  /**
   * 「标准产品」= 常规现货，进入官网“岩板产品系列”分类。「定制产品」= 客户按需定制的产品，选择后下方会出现“关联定制能力”字段。大部分情况保持「标准产品」。
   */
  catalogMode?: ('standard' | 'custom') | null;
  /**
   * 仅在“产品类型”选了「定制产品」时显示。选一项定制能力（如“定制颜色”“定制图案设计”），前台“定制产品”栏目会把本产品归入对应能力分组下。
   */
  customCapability?: (string | null) | CustomCapability;
  /**
   * 导入脚本写入的 /api/trade-media/... URL。这里是字符串，不是媒体上传。
   */
  coverImageUrl?: string | null;
  /**
   * 导入脚本写入的封面视频海报 URL。
   */
  coverVideoPosterUrl?: string | null;
  sortOrder?: number | null;
  /**
   * 该产品下的所有型号，可直接在此处新增或编辑，无需跳转到【产品型号】集合。
   */
  variants?: {
    docs?: (string | ProductVariant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * 记录哪些字段是 AI 从中文翻译来的。后台用来显示「AI 翻译」徽章，前端不读。
   */
  translationMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants".
 */
export interface ProductVariant {
  id: string;
  productRef: string | Product;
  code: string;
  size:
    | '800X2600mm'
    | '900X2700mm'
    | '900X3000mm'
    | '900X1800mm'
    | '1000X3000mm'
    | '1200X2400mm'
    | '1200X2700mm'
    | '1200X3200mm'
    | '1600X3200mm';
  /**
   * 前台厚度筛选从这里读取。自定义厚度会归入其他分类。
   */
  thickness?: ('3mm' | '6mm' | '9mm' | '12mm' | '15mm' | 'custom') | null;
  /**
   * 选了自定义后填写，如 20mm、30mm。仅用于展示，不影响筛选分组。
   */
  thicknessCustom?: string | null;
  process?:
    | (
        | '亮光'
        | '哑光'
        | '亮面(奢石釉)'
        | '真石镜面釉'
        | '肌肤釉'
        | '透光石'
        | '高白'
        | '数码模具面'
        | '火烧面'
        | '精雕'
        | '复刻釉'
        | '定位彩晶'
      )
    | null;
  colorGroup?:
    | ('白色' | '米白' | '黑色' | '灰色' | '米黄' | '棕色' | '金黄色' | '素色' | '蓝色' | '绿色' | '紫色' | '红色')
    | null;
  /**
   * 例如：单面 / 多面 / 四面
   */
  faceCount?: string | null;
  facePatternNote?: string | null;
  sortOrder?: number | null;
  /**
   * 产品材质表面纹理特写图。详情页“顶部大背景”和“材质纹理”画廊从这里读取，优先级最高。
   */
  elementImages?:
    | {
        /**
         * 上传新图片或从已有媒体里选择。这是唯一需要填的字段。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 解码后的相对文件路径，作为旧数据导入识别键。
         */
        sourcePath?: string | null;
        /**
         * R2 公开 URL，或旧的 /api/trade-media/... URL。
         */
        publicUrl?: string | null;
        altZh?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 产品在厨房、卫浴、客厅、背景墙等场景中的应用效果图。详情页“空间应用”画廊从这里读取。
   */
  spaceImages?:
    | {
        /**
         * 上传新图片或从已有媒体里选择。这是唯一需要填的字段。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 解码后的相对文件路径，作为旧数据导入识别键。
         */
        sourcePath?: string | null;
        /**
         * R2 公开 URL，或旧的 /api/trade-media/... URL。
         */
        publicUrl?: string | null;
        altZh?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 工地、施工现场、样板房等真实拍摄的照片。详情页“实拍图”画廊从这里读取。
   */
  realImages?:
    | {
        /**
         * 上传新图片或从已有媒体里选择。这是唯一需要填的字段。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 解码后的相对文件路径，作为旧数据导入识别键。
         */
        sourcePath?: string | null;
        /**
         * R2 公开 URL，或旧的 /api/trade-media/... URL。
         */
        publicUrl?: string | null;
        altZh?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 产品宣传视频或施工演示视频。详情页“视频”模块从这里读取。
   */
  videos?:
    | {
        /**
         * 上传新视频或从已有媒体里选择。这是唯一需要填的字段。
         */
        mediaRef?: (string | null) | Media;
        sourcePath?: string | null;
        publicUrl?: string | null;
        posterUrl?: string | null;
        titleZh?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * 文章的网址 ID，留空时由标题自动生成。发布后请勿修改，否则旧链接会失效。
   */
  slug: string;
  /**
   * 文章在前台显示的日期，用于排序。如需保存草稿，请使用右上角【保存草稿】按钮，无需修改此日期。
   */
  publishedAt: string;
  /**
   * 新闻列表卡片和文章页顶部使用此图，建议横版 16:9。
   */
  coverImage: string | Media;
  excerpt?: string | null;
  category?: ('company' | 'industry' | 'exhibition' | 'product') | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 记录哪些字段是 AI 从中文翻译来的。后台用来显示「AI 翻译」徽章，前端不读。
   */
  translationMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  name: string;
  role: string;
  /**
   * 保存时自动转为小写，用于查重。
   */
  email: string;
  company: string;
  /**
   * 网站 / WhatsApp / 电话 / 微信
   */
  contact: string;
  country: string;
  message: string;
  status: 'pending' | 'contacted' | 'resolved' | 'spam';
  /**
   * 仅后台可见，不会展示给提交人。
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'customCapabilities';
        value: string | CustomCapability;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'productVariants';
        value: string | ProductVariant;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customCapabilities_select".
 */
export interface CustomCapabilitiesSelect<T extends boolean = true> {
  capabilityKey?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  normalizedName?: T;
  published?: T;
  image?: T;
  description?: T;
  seriesTypes?: T;
  catalogMode?: T;
  customCapability?: T;
  coverImageUrl?: T;
  coverVideoPosterUrl?: T;
  sortOrder?: T;
  variants?: T;
  translationMeta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  productRef?: T;
  code?: T;
  size?: T;
  thickness?: T;
  thicknessCustom?: T;
  process?: T;
  colorGroup?: T;
  faceCount?: T;
  facePatternNote?: T;
  sortOrder?: T;
  elementImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  spaceImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  realImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        posterUrl?: T;
        titleZh?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  coverImage?: T;
  excerpt?: T;
  category?: T;
  body?: T;
  translationMeta?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  email?: T;
  company?: T;
  contact?: T;
  country?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wayon-overview_widget".
 */
export interface WayonOverviewWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wayon-quick-actions_widget".
 */
export interface WayonQuickActionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wayon-latest-inquiries_widget".
 */
export interface WayonLatestInquiriesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wayon-latest-news_widget".
 */
export interface WayonLatestNewsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wayon-workflow_widget".
 */
export interface WayonWorkflowWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}