/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    customCapabilities: CustomCapability;
    products: Product;
    productVariants: ProductVariant;
    news: News;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'productVariants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customCapabilities: CustomCapabilitiesSelect<false> | CustomCapabilitiesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productVariants: ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh' | 'en' | 'es' | 'ar')
    | ('zh' | 'en' | 'es' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'zh' | 'en' | 'es' | 'ar';
  widgets: {
    'zyl-overview': ZylOverviewWidget;
    'zyl-quick-actions': ZylQuickActionsWidget;
    'zyl-latest-inquiries': ZylLatestInquiriesWidget;
    'zyl-latest-news': ZylLatestNewsWidget;
    'zyl-workflow': ZylWorkflowWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * 图片的文字描述，用于 SEO 和无障碍访问，请简要说明图片内容。
   */
  alt: string;
  caption?: string | null;
  /**
   * 素材用途分类。产品图已由迁移脚本标记为“产品”，其他上传素材请选择对应分类。
   */
  category: 'product' | 'license' | 'showroom' | 'factory' | 'case-sales' | 'case-factory' | 'other';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customCapabilities".
 */
export interface CustomCapability {
  id: string;
  capabilityKey:
    | 'custom-thickness'
    | 'custom-cutting-processing'
    | 'custom-size'
    | 'custom-surface'
    | 'custom-color'
    | 'custom-pattern-design'
    | 'custom-hot-bending'
    | 'custom-logo-branding';
  title: string;
  description?: string | null;
  coverImage?: (string | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 管理官网展示的所有产品。新增产品的推荐顺序：① 填中文产品名 → ② 选产品系列 + 产品分类 → ③ 上传产品封面图 → ④ 在「产品规格」里补尺寸、厚度、颜色、工艺 → ⑤ 打开「发布到官网」。产品名称、产品介绍是多语言字段，用页面右上角的语言切换按 4 种语言分别填写；外语留空时官网会自动用英文兜底。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * 中文产品名（如「鱼肚金」）。英文、西班牙语、阿拉伯语版的官网页会自动用中文名的大写拼音显示（如「花开富贵」→「HUA KAI FU GUI」），外语栏一般可以留空。如需自定义外语名，在外语栏填写对应翻译，且不能含中文字符。
   */
  title: string;
  /**
   * 产品的唯一编号，例如 LV930R45。一个编号对应一个产品。列表页用大写显示，官网网址用小写。搜索时大小写都能匹配。
   */
  slug: string;
  /**
   * 产品的大写编号，例如 LV930R45。由系统从「产品型号」自动派生，请勿手动修改。
   */
  productCode?: string | null;
  /**
   * 导入工具自动生成的识别码，请勿手动修改。
   */
  normalizedName?: string | null;
  /**
   * 打开后官网会展示该产品。新建产品默认是关闭的，等图片、文案准备好再打开。
   */
  published?: boolean | null;
  /**
   * 官网产品列表卡片和详情页首屏的封面图。留空时官网会自动从下方「产品规格」的材质纹理图、实景应用图、工地实拍图里依次挑一张兜底。
   */
  image?: (string | null) | Media;
  /**
   * 该产品的规格信息（尺寸、厚度、工艺、颜色、产品图片）。可以直接在这里新增或修改。
   */
  variants?: {
    docs?: (string | ProductVariant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * 板材的长×宽（毫米）。官网「规格」筛选从这里读取。
   */
  size?:
    | (
        | '800X2600mm'
        | '900X2700mm'
        | '900X3000mm'
        | '900X1800mm'
        | '1000X3000mm'
        | '1200X2400mm'
        | '1200X2700mm'
        | '1200X3200mm'
        | '1600X3200mm'
      )
    | null;
  /**
   * 官网「厚度」筛选从这里读取。常见厚度选下拉项；其他厚度选「自定义」并在下方填写。
   */
  thickness?: ('3mm' | '6mm' | '9mm' | '12mm' | '15mm' | 'custom') | null;
  /**
   * 如 20mm、30mm 等非标厚度。仅在板材厚度选了「自定义」后出现。
   */
  thicknessCustom?: string | null;
  /**
   * 板材表面处理工艺。官网「表面工艺」筛选从这里读取。
   */
  process?:
    | (
        | '亮光'
        | '哑光'
        | '亮面(奢石釉)'
        | '真石镜面釉'
        | '肌肤釉'
        | '透光石'
        | '高白'
        | '数码模具面'
        | '火烧面'
        | '精雕'
        | '复刻釉'
        | '定位彩晶'
      )
    | null;
  /**
   * 官网「颜色」筛选从这里读取。
   */
  colorGroup?:
    | ('白色' | '米白' | '黑色' | '灰色' | '米黄' | '棕色' | '金黄色' | '素色' | '蓝色' | '绿色' | '紫色' | '红色')
    | null;
  /**
   * 例如：单面 / 多面 / 四面。可留空。
   */
  faceCount?: string | null;
  /**
   * 对纹理的简短描述，可留空。
   */
  facePatternNote?: string | null;
  /**
   * 板材表面纹理的特写照片。官网详情页的顶部大背景和「材质纹理」画廊从这里读取，是产品最重要的展示图。
   */
  elementImages?:
    | {
        /**
         * 上传新图片或从媒体库里选一张。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 系统导入时自动填写，请勿手动修改。
         */
        sourcePath?: string | null;
        /**
         * 系统自动填写。
         */
        publicUrl?: string | null;
        /**
         * 用于无障碍阅读和 SEO，可留空。
         */
        altZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 板材在厨房、卫浴、客厅、背景墙等场景中的应用效果图。官网详情页的「空间应用」画廊从这里读取。
   */
  spaceImages?:
    | {
        /**
         * 上传新图片或从媒体库里选一张。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 系统导入时自动填写，请勿手动修改。
         */
        sourcePath?: string | null;
        /**
         * 系统自动填写。
         */
        publicUrl?: string | null;
        /**
         * 用于无障碍阅读和 SEO，可留空。
         */
        altZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 工地、施工现场、样板房的真实照片。官网详情页的「实拍图」画廊从这里读取。
   */
  realImages?:
    | {
        /**
         * 上传新图片或从媒体库里选一张。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 系统导入时自动填写，请勿手动修改。
         */
        sourcePath?: string | null;
        /**
         * 系统自动填写。
         */
        publicUrl?: string | null;
        /**
         * 用于无障碍阅读和 SEO，可留空。
         */
        altZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 产品宣传视频或施工演示视频。官网详情页的「视频」模块从这里读取。
   */
  videos?:
    | {
        /**
         * 上传新视频或从媒体库里选一个。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        sourcePath?: string | null;
        publicUrl?: string | null;
        /**
         * 视频未播放时显示的封面图，可留空。
         */
        posterUrl?: string | null;
        titleZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 常规现货选「常规产品」（归入官网「岩板系列」入口），客户定制款选「定制产品」（选了之后下方会出现「定制类型」字段）。多数情况选常规。
   */
  catalogMode?: ('standard' | 'custom') | null;
  /**
   * 仅「定制产品」时填写。选一种定制类型（如「定制颜色」「定制图案」），官网「定制产品」栏目会把本产品归入对应分组。
   */
  customCapability?: (string | null) | CustomCapability;
  /**
   * 多语言字段。请用页面右上角的语言切换分别填写中/英/西/阿四种语言的真实翻译，不要把中文复制到外语栏。
   */
  description?: string | null;
  /**
   * 官网「岩板系列」里的子分类（质感岩板、名石岩板、洞石岩板、木纹岩板等），可多选。尺寸、厚度、颜色、工艺这些是官网另外的筛选入口，会从「产品规格」自动归类，不在这里填。
   */
  seriesTypes?:
    | (
        | '质感岩板'
        | '名石岩板'
        | '洞石岩板'
        | '木纹岩板'
        | '护墙岩板'
        | '艺术岩板'
        | '连纹岩板'
        | '创意网红'
        | '新品系列'
        | '特惠系列'
      )[]
    | null;
  /**
   * 系统导入时自动填写，请勿手动修改。
   */
  coverImageUrl?: string | null;
  /**
   * 系统导入时自动填写，请勿手动修改。
   */
  coverVideoPosterUrl?: string | null;
  /**
   * 数字越小越靠前。默认 0。
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 产品的规格信息（尺寸、厚度、表面工艺、颜色、产品图片、视频）。每个产品对应一条规格。产品名称、产品介绍、封面图等通用信息在「产品」集合编辑。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants".
 */
export interface ProductVariant {
  id: string;
  /**
   * 这条规格属于哪个产品。
   */
  productRef: string | Product;
  /**
   * 对应产品的唯一编号，例如 LV930R45。
   */
  code: string;
  /**
   * 板材的长×宽（毫米）。官网「规格」筛选从这里读取。
   */
  size:
    | '800X2600mm'
    | '900X2700mm'
    | '900X3000mm'
    | '900X1800mm'
    | '1000X3000mm'
    | '1200X2400mm'
    | '1200X2700mm'
    | '1200X3200mm'
    | '1600X3200mm';
  /**
   * 官网「厚度」筛选从这里读取。常见厚度选下拉项；其他厚度选「自定义」并在下方填写。
   */
  thickness?: ('3mm' | '6mm' | '9mm' | '12mm' | '15mm' | 'custom') | null;
  /**
   * 如 20mm、30mm 等非标厚度。仅在板材厚度选了「自定义」后出现。
   */
  thicknessCustom?: string | null;
  /**
   * 板材表面处理工艺。官网「表面工艺」筛选从这里读取。
   */
  process?:
    | (
        | '亮光'
        | '哑光'
        | '亮面(奢石釉)'
        | '真石镜面釉'
        | '肌肤釉'
        | '透光石'
        | '高白'
        | '数码模具面'
        | '火烧面'
        | '精雕'
        | '复刻釉'
        | '定位彩晶'
      )
    | null;
  /**
   * 官网「颜色」筛选从这里读取。
   */
  colorGroup?:
    | ('白色' | '米白' | '黑色' | '灰色' | '米黄' | '棕色' | '金黄色' | '素色' | '蓝色' | '绿色' | '紫色' | '红色')
    | null;
  /**
   * 例如：单面 / 多面 / 四面。可留空。
   */
  faceCount?: string | null;
  /**
   * 对纹理的简短描述，可留空。
   */
  facePatternNote?: string | null;
  /**
   * 数字越小越靠前。默认 0。
   */
  sortOrder?: number | null;
  /**
   * 板材表面纹理的特写照片。官网详情页的顶部大背景和「材质纹理」画廊从这里读取，是产品最重要的展示图。
   */
  elementImages?:
    | {
        /**
         * 上传新图片或从媒体库里选一张。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 系统导入时自动填写，请勿手动修改。
         */
        sourcePath?: string | null;
        /**
         * 系统自动填写。
         */
        publicUrl?: string | null;
        /**
         * 用于无障碍阅读和 SEO，可留空。
         */
        altZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 板材在厨房、卫浴、客厅、背景墙等场景中的应用效果图。官网详情页的「空间应用」画廊从这里读取。
   */
  spaceImages?:
    | {
        /**
         * 上传新图片或从媒体库里选一张。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 系统导入时自动填写，请勿手动修改。
         */
        sourcePath?: string | null;
        /**
         * 系统自动填写。
         */
        publicUrl?: string | null;
        /**
         * 用于无障碍阅读和 SEO，可留空。
         */
        altZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 工地、施工现场、样板房的真实照片。官网详情页的「实拍图」画廊从这里读取。
   */
  realImages?:
    | {
        /**
         * 上传新图片或从媒体库里选一张。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        /**
         * 系统导入时自动填写，请勿手动修改。
         */
        sourcePath?: string | null;
        /**
         * 系统自动填写。
         */
        publicUrl?: string | null;
        /**
         * 用于无障碍阅读和 SEO，可留空。
         */
        altZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 产品宣传视频或施工演示视频。官网详情页的「视频」模块从这里读取。
   */
  videos?:
    | {
        /**
         * 上传新视频或从媒体库里选一个。只需填这一项即可。
         */
        mediaRef?: (string | null) | Media;
        sourcePath?: string | null;
        publicUrl?: string | null;
        /**
         * 视频未播放时显示的封面图，可留空。
         */
        posterUrl?: string | null;
        titleZh?: string | null;
        /**
         * 数字越小越靠前。默认 0。
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 多语言新闻：标题、摘要、正文需要按 4 个语种分别填写。请使用页面右上角的语言切换器逐个语言录入内容；切换语言后保存只会保存当前语言的内容。某语种留空时，前台会自动回落显示英文；若英文也为空，该语种页面不会展示这条新闻。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  /**
   * 多语言字段，请在每个语言下分别填写真实的目标语言翻译（不要把中文复制到英文/西语/阿语字段，前台会判定为未翻译并自动回落英文）。
   */
  title: string;
  /**
   * 文章的网址 ID，留空时由标题自动生成。发布后请勿修改，否则旧链接会失效。
   */
  slug: string;
  /**
   * 文章在前台显示的日期，用于排序。如需保存草稿，请使用右上角【保存草稿】按钮，无需修改此日期。
   */
  publishedAt: string;
  /**
   * 新闻列表卡片和文章页顶部使用此图，建议横版 16:9。
   */
  coverImage: string | Media;
  /**
   * 多语言字段，请在每个语言下分别填写真实的目标语言翻译（不要把中文复制到英文/西语/阿语字段）。某语种留空或仅含中文时回落显示英文摘要；英文也为空时前台不显示摘要。
   */
  excerpt?: string | null;
  category?: ('company' | 'industry' | 'exhibition' | 'product') | null;
  /**
   * 多语言字段，请在每个语言下分别填写真实的目标语言翻译（不要把中文复制到英文/西语/阿语字段，前台会判定为未翻译）。
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  name: string;
  role: string;
  /**
   * 保存时自动转为小写，用于查重。
   */
  email: string;
  company: string;
  /**
   * 网站 / WhatsApp / 电话 / 微信
   */
  contact: string;
  country: string;
  message: string;
  status: 'pending' | 'contacted' | 'resolved' | 'spam';
  /**
   * 仅后台可见，不会展示给提交人。
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'customCapabilities';
        value: string | CustomCapability;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'productVariants';
        value: string | ProductVariant;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customCapabilities_select".
 */
export interface CustomCapabilitiesSelect<T extends boolean = true> {
  capabilityKey?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  productCode?: T;
  normalizedName?: T;
  published?: T;
  image?: T;
  variants?: T;
  size?: T;
  thickness?: T;
  thicknessCustom?: T;
  process?: T;
  colorGroup?: T;
  faceCount?: T;
  facePatternNote?: T;
  elementImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  spaceImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  realImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        posterUrl?: T;
        titleZh?: T;
        sortOrder?: T;
        id?: T;
      };
  catalogMode?: T;
  customCapability?: T;
  description?: T;
  seriesTypes?: T;
  coverImageUrl?: T;
  coverVideoPosterUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  productRef?: T;
  code?: T;
  size?: T;
  thickness?: T;
  thicknessCustom?: T;
  process?: T;
  colorGroup?: T;
  faceCount?: T;
  facePatternNote?: T;
  sortOrder?: T;
  elementImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  spaceImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  realImages?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        altZh?: T;
        sortOrder?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        mediaRef?: T;
        sourcePath?: T;
        publicUrl?: T;
        posterUrl?: T;
        titleZh?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  coverImage?: T;
  excerpt?: T;
  category?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  email?: T;
  company?: T;
  contact?: T;
  country?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zyl-overview_widget".
 */
export interface ZylOverviewWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zyl-quick-actions_widget".
 */
export interface ZylQuickActionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zyl-latest-inquiries_widget".
 */
export interface ZylLatestInquiriesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zyl-latest-news_widget".
 */
export interface ZylLatestNewsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zyl-workflow_widget".
 */
export interface ZylWorkflowWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}